# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    client_repository:
      class: AppBundle\Repository\ClientRepository
      factory: ['@doctrine.orm.entity_manager', getRepository]
      arguments:
        - AppBundle\Entity\Client

    invoice_form:
      class: AppBundle\Form\InvoiceForm
      arguments: ['@client_repository', '@security.token_storage']
      tags:
        - { name: form.type }